apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: generic-admin
      property: username
  - secretKey: password
    remoteRef:
      key: generic-admin
      property: password
