apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1h
  timeout: 10m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 85.3.3
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
      valuesFiles:
        - values.yaml
  targetNamespace: monitoring
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
