---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  path: ./infra/controllers/external-secrets/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-deploy
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  dependsOn:
    - name: external-secrets-crds
  path: ./infra/controllers/external-secrets/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-resources
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  dependsOn:
    - name: external-secrets-deploy
  path: ./infra/controllers/external-secrets/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
