---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: home-lab
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infra
      originRevision: "@home-lab"
      copy:
        - from: "@home-lab/infra/**"
          to: "@artifact/"
    - name: apps
      originRevision: "@home-lab"
      copy:
        - from: "@home-lab/apps/**"
          to: "@artifact/"
