apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  interval: 1h
  releaseName: proxmox-csi-plugin
  chart:
    spec:
      chart: proxmox-csi-plugin
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi
        namespace: csi-proxmox
  targetNamespace: csi-proxmox
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    existingConfigSecret: proxmox-csi-plugin
    storageClass:
    - name: proxmox-csi
      cache: writethrough
      fstype: ext4
      reclaimPolicy: Retain
      ssd: true
      storage: vm_data
      mountOptions:
      - noatime
