apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: generic-admin
  namespace: default
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: generic-admin
    creationPolicy: Owner
  data:
  - secretKey: admin-username
    remoteRef:
      key: generic-admin
      property: username
  - secretKey: admin-password
    remoteRef:
      key: generic-admin
      property: password
