---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-deploy
  namespace: flux-system
spec:
  targetNamespace: traefik
  path: ./infra/traefik/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-resources
  namespace: flux-system
spec:
  targetNamespace: traefik
  dependsOn:
    - name: traefik-deploy
  path: ./infra/traefik/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
